# Generated by Django 3.1.1 on 2020-09-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
