# Generated by Django 3.1.1 on 2020-09-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
    ]
